"Execucao do gerenciador de plugins"
execute pathogen#infect()

"Remapear atalho Emmet"
let g:user_emmet_leader_key=','

"Esquema de cores escuro"
colorscheme Tomorrow-Night-Eighties

"Tamanho da indentacao"
set tabstop=2

"Identifica o tipo de arquivo e indenta"
filetype plugin indent on

"colore o editor"
syntax on

"herda a indentacao com o tamanho do tab"
set shiftwidth=2

"comportamento usual do backspace"
set backspace=2

"Esse comando numera as linhas"
set number

"fazer calculo da distancia das linhas"
set relativenumber

"busca incremental feedback durante busca"
set incsearch

"destaque nos resultados"
set hlsearch

"salvar na codificacao desejada"
set fileencoding=iso-8859-1

"visualizar na codificação desejada"
set encoding=iso-8859-1

"usar espaços no lugar de tabs"
set expandtab

"backspace respeitar indentacao"
set softtabstop=2
